---
title: "Casos reportados de 2019-nCoV"
author: "Ciencia Abierta, Fuente: https://github.com/beoutbreakprepared/nCoV2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    theme: cerulean
    #source_code: embed
---

```{r setup, include = FALSE}
library(flexdashboard)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(raster)
library(stringr)

sites_out_hubei <- read.csv("https://raw.githubusercontent.com/beoutbreakprepared/nCoV2019/master/dataset_archive/ncov_outside_hubei_20200128%200000.csv")

sites_hubei <- read.csv("https://raw.githubusercontent.com/beoutbreakprepared/nCoV2019/master/dataset_archive/ncov_hubei_20200128%200000.csv")

sites <- rbind(sites_out_hubei, sites_hubei)


## Delete any space at the start or end
sites$province <- str_trim(sites$province)
sites$country <- str_trim(sites$country)

sites$country2 <- ifelse(sites$country == "China", "orange","green")


## cases per city 
cases_per_city <- 
  sites %>% 
  group_by(city, country, latitude, longitude, country2) %>% 
  tally()

cases_per_city$n2 <- ifelse(cases_per_city$n >= 10, "red","green")
cases_per_city$size <- ifelse(cases_per_city$country == "China", 0.05, 1)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Casos mundiales confirmados de 2019-nCoV 
```{r}
leaflet() %>% 
  addTiles() %>% 
  addProviderTiles("CartoDB.Positron") %>%
  #fitBounds(-127.44,24.05,-65.30,50.35) %>% 
  addCircleMarkers(cases_per_city$longitude, 
                   cases_per_city$latitude, 
                   color = cases_per_city$n2, 
                   #radius = cases_per_city$n/5, 
                   radius = cases_per_city$size,
                   fill = T,
                   fillOpacity = 0.2,
                   opacity = 0.5,
                   popup = paste(cases_per_city$country,
                                 cases_per_city$city, 
                                 cases_per_city$n,
                                 sep = ", ")) %>% 
  addLegend("bottomleft", 
            colors = c("red","green"),
            labels = c("N >= 10",
                       "N < 10"), 
            opacity = 0.8)
```


### Casos confirmados de 2019-nCoV en China 

```{r}
chinaMap<-getData('GADM',country="CHN",level=1, path = "data/")

china_sr <- 
  sites %>% 
  filter(country == "China")

china_sr_n <- 
  china_sr %>% 
  count(province)

## Correct spelling
chinaMap$NAME_1[grep("Mo", chinaMap$NAME_1)] <- "Inner Mongolia"
chinaMap$NAME_1[grep("Nin", chinaMap$NAME_1)] <- "Ningxia"
chinaMap$NAME_1[grep("Xinjiang", chinaMap$NAME_1)] <- "Xinjiang"

chinaMap$n <- china_sr_n$n[match(chinaMap$NAME_1, china_sr_n$province)]

#create a pop up (onClick)
polygon_popup <- paste0("<strong>Provincia: </strong>", chinaMap$NAME_1, "<br>",
                        "<strong>N: </strong>", round(chinaMap$n,2))

#create a color palette to fill the polygons
pal <- colorQuantile("Reds", NULL, n = 10)

map = leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = chinaMap, 
              fillColor= ~pal(n),
              fillOpacity = 2, 
              weight = 1, 
              color = "grey",
              popup = polygon_popup)


map
```

